### ISSUE TITLE
unknown "Pathname"

### ISSUE THREAD

**Issue by sroller** [exiftool-rb/exiftool.rb#13]
it should be mentioned that one has to require 'pathname'

**Comment by morozgrafix** [comment]
Thanks for opening this issue. We haven't touched this gem in a while and I would like to spend some more time on getting it into a better shape. 

Can you please elaborate on the `pathname` dependency and I will look into it?

Thanks.

**Comment by morozgrafix** [comment]
@sroller I'm going to close this issue since it hasn't had any activity in over a year. Feel free to reopen it if you still having issues. Thanks.

**Comment by sroller** [comment]
I must have missed the update from 11-SEP-2019. I believe the demo snippets didn't run without `require "pathname"` but I cannot reproduce it anymore. Might have been a glitch on my system.

**Comment by morozgrafix** [comment]
Thanks for your response. I will keep it closed then. If you see it come up again feel free to reopen this issue.
