### ISSUE TITLE
Compatibility Inquiry: Exiftool 1.2.4 or 1.2.3 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [exiftool-rb/exiftool.rb#42]
Hi,

I'm seeking confirmation regarding the compatibility of the Exiftool 1.2.4 or 1.2.3  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems and github(https://github.com/exiftool-rb/exiftool.rb/blob/master/.github/workflows/build.yml) it only specifies a minimum required Ruby version of > 2.4 and matrix: ruby-version: ['3.0', '3.1', '3.2'] respectively. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by morozgrafix** [comment]
Thank you for bringing it up. I will add Ruby 3.3.0 to our tests and report back in this thread.

**Comment by morozgrafix** [comment]
I've added testing against Ruby 3.3.0. Version 1.2.4 of the exiftool.rb tests have passed. I released  [exiftool v1.2.5](https://rubygems.org/gems/exiftool/versions/1.2.5) which includes testing on Ruby 3.3.0
Additionally [exiftool_vendored v12.76.1](https://rubygems.org/gems/exiftool_vendored/versions/12.76.1) has been updated after testing against Ruby 3.3.0.

**Comment by sydverisk** [comment]
Thank you so much for the update I appreciate it!
